DROP TABLE IF EXISTS `Meal_Types`;
DROP TABLE IF EXISTS `Cuisines`;
DROP TABLE IF EXISTS `Recipes`;
DROP TABLE IF EXISTS `Starches`;
DROP TABLE IF EXISTS `Proteins`;

CREATE TABLE Starches(
	id INT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	calories INT(11)
)ENGINE=InnoDB;

CREATE TABLE Proteins(
	id INT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	calories INT(11)
)ENGINE=InnoDB;

CREATE TABLE Recipes(
	id INT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	cold BOOL,
	vegetarian BOOL,
	crowd BOOL,
	quick BOOL,
	Protein_ID INT(6),
	Starch_ID INT(6),
	Type_ID INT(6),
	FOREIGN KEY (Protein_ID) REFERENCES Proteins(id) ON DELETE CASCADE,
	FOREIGN KEY (Starch_ID) REFERENCES Starches(id) ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE Meal_Types(
	id INT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	Recipe_ID INT(6),
	FOREIGN KEY (Recipe_ID) REFERENCES Recipes(id) ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE Cuisines(
	id INT(6) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	Recipe_ID INT(6),
	FOREIGN KEY (Recipe_ID) REFERENCES Recipes(id) ON DELETE CASCADE
)ENGINE=InnoDB;


ALTER TABLE Recipes ADD FOREIGN KEY (Type_ID) REFERENCES Meal_Types(id) ON DELETE CASCADE;